# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b415594d2cc28f3641dd31c165813b31b645a35c214a0a9d17897c11917fe5740b851a41d7df0cd88cfd87d9531db67438276bfe821ca33930b246beae0fbe6

test:
  secret_key_base: 12e6a5451917acd4c6f3196afbfebacaac866dfbed7ce4508208403f09ac05d183b778788da58c68dbf99d6ae874f9bcbf63559fa8c23b080bec89fc9058dcd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
